import "./globals.css"

import type { Metadata } from "next"

import { finalSix } from "@/config/fonts"

export const metadata: Metadata = {
  title: "CNA | Recrutamento",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={finalSix.className}>{children}</body>
    </html>
  )
}
